### ISSUE TITLE
Migrondi: command not found

### ISSUE THREAD

**Issue by jacksonpradolima** [AngelMunoz/Migrondi#15]
Hi,
I installed Migrondi using the command `dotnet tool install --global Migrondi` on Windows and Ubuntu 18.04. However, on Ubuntu it show the message: `command not found`. If I try to install again I receive the message: `Tool 'migrondi' is already installed.`. What could be?

dotnet SDKs:
- 3.1.407
- 5.0.201

**Comment by AngelMunoz** [comment]
Interesting hmm I have no idea what can be happening there while this [SO Q&A](https://stackoverflow.com/a/55442808) is not 100% your case I suggest you to look at it particularly these steps

- Does the tool exist under ~/.dotnet/tools?
- Have you tried restarting the command prompt to force refresh your $PATH?

also I'd also ask you 
- is your ~/.dotnet/tools in your $PATH?
- how did you install dotnet; via the snap or the deb package?

if none of those seem to work I'd like you to try installing it as a local tool

```
dotnet new tool-manifest
dotnet tool install Migrondi
dotnet migrondi --help
```

**Comment by jacksonpradolima** [comment]
> Does the tool exist under ~/.dotnet/tools?

 Yes

> how did you install dotnet; via the snap or the deb package?

Deb package, following these steps [here](https://docs.microsoft.com/en-us/dotnet/core/install/linux-ubuntu#1804-) from Microsoft website.

> if none of those seem to work I'd like you to try installing it as a local tool

Now, it is executing. However, when I apply the `up` command to create a new table: `Migrations Applied: 0`
Using Windows it is working very well.

**Comment by AngelMunoz** [comment]
> >Does the tool exist under ~/.dotnet/tools?

> Yes

does that directory is in the $PATH env variable?

sorry it's taking long I was just trying to get an ubuntu environment to try to replicate it I'll try to get back if I find something in the following days

**Comment by AngelMunoz** [comment]
hey @jacksonpradolima did you have a chance to check if this one  is still happening?

**Comment by AngelMunoz** [comment]
I had finally setup my Raspberry Pi 4 with Ubuntu server and I did find some issues with SQLite I'll reserve some time next week to check it out
```
Unable to load shared library 'SQLite.Interop.dll' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libSQLite.Interop.dll: cannot open shared object file: No such file or directory
```
so this might need a little bit more of exploration, not sure if it's due to the arm arch though

**Comment by AngelMunoz** [comment]
So... using WSL2 Ubuntu everything seems to work just fine
```
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.2 LTS
Release:        20.04
Codename:       focal
```
![image](https://user-images.githubusercontent.com/8684875/127581919-c994358b-6a52-4f80-8b25-66b28108b05c.png)
So the Raspberry Pi Issue can be ruled out, also it doesn't seem to reproduce your initial error
I'll wait for your feedback

**Comment by jacksonpradolima** [comment]
Hi @AngelMunoz 

We finished the project, and we are using Windows. Unfortunately, I can't give you good feedback.

We can close this issue.
