### ISSUE TITLE
dotnet tool?

### ISSUE THREAD

**Issue by panesofglass** [AngelMunoz/Migrondi#2]
Have you considered publishing this as a global or local tool? That might make it a bit more accessible to people.

**Comment by AngelMunoz** [comment]
I did think about it, but I wanted to take a general approach first to make it available not just for dotnet people, I remember a few years ago working with a nodejs project and had precisely the need for a tool like this

but I will try to look into making it a dotnet-tool as well

**Comment by AngelMunoz** [comment]
I just gave it a try and this should be available to install as a global dotnet tool once nuget finishes with the package indexing 😁 

https://www.nuget.org/packages/Migrondi/0.4.0

thanks, @panesofglass  to bring this to my attention
if you find any issues/bugs with the dotnet tool please let me know
