### ISSUE TITLE
Running the migrondi command immediately kills the migrondi process

### ISSUE THREAD

**Issue by EverybodyKurts** [AngelMunoz/Migrondi#29]
**Describe the bug**

Trying to invoke the `migrondi` command immediately invokes a pid killed error.

**To Reproduce**

```bash
app git:(main) ✗ dotnet tool install --global Migrondi
You can invoke the tool using the following command: migrondi
Tool 'migrondi' (version '0.7.0') was successfully installed.
➜  app git:(main) ✗ migrondi
[1]    10871 killed     migrondi
```

**Expected behavior**

**Screenshots**

![Screen Shot 2021-08-22 at 12 37 54 PM](https://user-images.githubusercontent.com/879734/130363053-b65e5580-49ff-4a52-8fba-c242831d77cf.png)

**Desktop (please complete the following information):**
 - OS: macOS Big Sur

**Comment by AngelMunoz** [comment]
hmm, this is very very weird, I was not able to produce that result as well, I'm not sure if I have/not have something else on the machine not sure if there's more info you can provide about it

![image](https://user-images.githubusercontent.com/8684875/130653152-4e6a55a0-c297-4b67-a135-950b2053a50e.png)

**Comment by AngelMunoz** [comment]
Although, I should print the usage in case no arguments are provided, and add a "--version" arg as well

**Comment by jimmyroberts** [comment]
Do you need help with m1 testing? If so, I have one. :) Let me know how I can assist.
![image](https://user-images.githubusercontent.com/11284104/142752711-384a170a-66be-489b-92e7-91d88670c03e.png)

**Comment by jimmyroberts** [comment]
My dotnet verision:

![image](https://user-images.githubusercontent.com/11284104/142752737-5c33ec2d-fb4c-4289-a2af-49a4725703a7.png)

**Comment by AngelMunoz** [comment]
with .NET6 being stable now, I think this should have been solved, if you could do a couple of migrations in either sqlite or any sql database you have laying around it would be nice.

if all seems to go well we should be able to close this issue

> Although, we might need to fix the version command

**Comment by AngelMunoz** [comment]
we're at net8 with net9 around the corner, if this is still a thing, please feel free to re-open
