### ISSUE TITLE
Wrong directory when using Migrondi for the first time in OSX.

### ISSUE THREAD

**Issue by Swoorup** [AngelMunoz/Migrondi#3]
```
{
  "connection": "Data Source=migrondi.db",
  "migrationsDir": "/",
  "driver": "sqlite"
}
```

Migrondi set the directory to root. Think it should rather be './'?

**Comment by AngelMunoz** [comment]
It should I'll check it and come back to you

**Comment by AngelMunoz** [comment]
I just checked in a fix for this the actual migrationsDir should be`"migrations/"` from now on

**Comment by AngelMunoz** [comment]
version 0.4.1 has been released to NuGet and  binaries to the releases tab
`dotnet tool install --global Migrondi --version 0.4.1`
