### ISSUE TITLE
Could not migrate stored procedure for Microsoft SQL Server

### ISSUE THREAD

**Issue by twuttiwat** [AngelMunoz/Migrondi#4]
Hi there,

I am trying to migrate stored procedure for SQL Server with Migrondi.
But I received following error when run 'migrondi up'

> Unexpected Exception 'CREATE/ALTER PROCEDURE' must be the first statement in a query batch.

Here is the doc from MSDN (https://docs.microsoft.com/en-us/sql/t-sql/statements/create-procedure-transact-sql?view=sql-server-ver15)

One work around is to wrap whole procedure inside Execute like this
```

EXEC ('create procedure dbo.test
  as
  begin
    select * from some_table
  end')

```

Thank you very much,
Teerawat

**Comment by AngelMunoz** [comment]
I've been trying to figure out what is an ideal solution for this but I can't really think what's a better approach than `Exec`.
one solution that I've seen often in StackOverflow is to use 
```tsql
GO -- <- this one right here
create procedure dbo.test
    as
    begin
        select * from some_table
    end
```

but I'm not sure if that interferes with the transaction of the migration itself other than that I don't think `Exec` is a bad approach either, at least it doesn't seem to be a discouraged approach, do you have any ideas of what can we do about this or is Exec enough in practice?

**Comment by brettrowberry** [comment]
The `GO` batch separator appears all over our migration scripts, as does `EXEC`.

**Comment by brettrowberry** [comment]
In SQL Server, a transaction can have multiple batches. 
https://bertwagner.com/posts/what-does-the-go-command-do/

https://brianflove.com/2015-06-02/multiple-batches-in-a-single-transaction/

**Comment by AngelMunoz** [comment]
I'll proceed to close this, feel free to reopen if necessary
