### ISSUE TITLE
Validate new migration names

### ISSUE THREAD

**Issue by VitorRigoni** [AngelMunoz/Migrondi#8]
Hello! It's me again! 😁

I just noticed something I think we can improve, and I wanted to discuss with you:

When creating a new migration with `migrondi new -n MyMigration`, migrondi will create the migration file with any name you set. For example, `migrondi new -n My_Migration` is created properly, but `migrondi up` will fail because `My_Migration` is not a valid name.

I see we already have the validation functions, so I was thinking it'd be a nice to have if we could validate on `new` as well.

What do you think?

**Comment by AngelMunoz** [comment]
Hey there! 
Well, I got inspired yesterday thanks to you so I refactored the `Program.fs` file so it is friendlier to newcomers (hopefully) and perhaps this was addressed, would you mind checking on the latest changes of the master branch?

if it keeps failing as you mentioned we can validate in this line
https://github.com/AngelMunoz/Migrondi/blob/master/src/Migrondi/Migrations.fs#L30 as well as this one https://github.com/AngelMunoz/Migrondi/blob/master/src/Migrondi/Utils.fs#L78
I think most names are valid except for the underscore as you mentioned the up command looks tries to check for the valid name here https://github.com/AngelMunoz/Migrondi/blob/master/src/Migrondi/Utils.fs#L181

I know it's kind of messy 😫
but I can think of a few ways of dealing with this 
- fail inside `Migrations.fs` when passing a bad name
- fail inside  `Utils.fs` when passing a bad name
- or Addapt `Utils.fs:181` to allow for more underscores and just verify that the last segment is a timestamp + .SQL

what do you think?

**Comment by VitorRigoni** [comment]
Oh that's great! `Program.fs` definitely looks a lot nicer now!

As I was going through the code a question popped in my head but I realize you already answered that question!
My question was: how important is it that we validate the file name format? Can we simply check if we have the timestamp at the end of the file name?

And I think that your last suggestion answers this. We could, for example, regex on `(.)+_([0-9]+).sql` to make sure it's a valid format and verify the number combination is a valid timestamp. That would ensure we have the most important piece (the timestamp) while giving the user the flexibility to write the name however they prefer.

With that, I think we can avoid applying the validation on a new migration since we'll effectively accept any name and we only need to validate when applying to ensure the user hasn't messed with the timestamp we need.

To me, that seems like a good direction to take!

**Comment by AngelMunoz** [comment]
That sounds like a good strategy then, would you feel brave to take a stab at this?
we would also need to update this test
https://github.com/AngelMunoz/Migrondi/blob/master/src/Migrondi.Tests/Tests.fs#L92

**Comment by VitorRigoni** [comment]
Oh yes, absolutely! I may not be able to do this today, but I think I can get this done next week 😁

**Comment by AngelMunoz** [comment]
NuGet package is out and a release has been added, thanks @VitorRigoni
